name: Mutation Testing

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  Tests:
    name: PHP ${{ matrix.php }} + Infection
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Install PHP
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          update: true

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run Infection with PHPUnit
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --coverage-xml=build/logs/coverage-xml --log-junit=build/logs/phpunit.junit.xml
          vendor/bin/infection --threads=2 --coverage=build/logs --show-mutations --no-progress --min-covered-msi=100
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
