name: Static Analysis

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  PHPStan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install PHP
        uses: shivammathur/setup-php@2.14.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          update: true

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update $DEFAULT_COMPOSER_FLAGS

      - name: PHPStan tests
        run: vendor/bin/phpstan analyze -l 8 -a vendor/yiisoft/yii2/Yii.php --no-progress src
